### ISSUE TITLE
In Remove you error out on lots of cases that might be able to be ignored.

### ISSUE THREAD

**Issue by rhatdan** [shishir-a412ed/docker-lvm-driver#12]
```
func (l *lvmDriver) Remove(req volume.Request) volume.Response {
    l.Lock()
    defer l.Unlock()

    if err := os.RemoveAll(getMountpoint(l.home, req.Name)); err != nil {
# Should this be ignored if you get ERR=ENOEXIST?
        return resp(err)
    }

    vgName, err := getVolumegroupName(l.vgConfig)
    if err != nil {
        return resp(err)
    }

    cmd := exec.Command("lvremove", "--force", fmt.Sprintf("%s/%s", vgName, req.Name))
    if out, err := cmd.CombinedOutput(); err != nil {
        return resp(fmt.Errorf("%s", string(out)))
    }

    v := l.volumes[req.Name]
    delete(l.count, v)
    delete(l.volumes, req.Name)
    if err := saveToDisk(l.volumes, l.count); err != nil {
        return resp(err)
    }
# Should this happen even if the above fails?
    return resp(getMountpoint(l.home, req.Name))
}
```

**Comment by shishir-a412ed** [comment]
@rhatdan If the location (Mountpoint: e.g /var/lib/docker-lvm/foobar) does not exist. `os.RemoveAll` would return no error (err == nil).

`os.RemoveAll` description from golang.org
`RemoveAll removes path and any children it contains. It removes everything it can but returns the first error it encounters. If the path does not exist, RemoveAll returns nil (no error).`

**Comment by rhatdan** [comment]
Ok thats great. I still am not crazy about leaving all of this other random data that might be able to cleanedup.  Not sure there is a good fix for this.

**Comment by shishir-a412ed** [comment]
@rhatdan 
Random data ?

**Comment by rhatdan** [comment]
Basically if something fails in the stack, how do I cleanup the other data.

**Comment by rhatdan** [comment]
Closing as this is the best we can do.
