### ISSUE TITLE
Makefile should use $(DESTDIR)

### ISSUE THREAD

**Issue by rhatdan** [shishir-a412ed/docker-lvm-driver#13]
When building this in to a spec, you need to be able to do something like

make DESTDIR=/tmp/foobar install

And have all of the content end up under /tmp/foobar.

**Comment by shishir-a412ed** [comment]
@rhatdan 
https://github.com/shishir-a412ed/docker-lvm-plugin/commit/76bdb11a83db4277cff1288b340cb9677d970efb

are these the right places to prefix $(DESTDIR) ?

**Comment by shishir-a412ed** [comment]
Fixed in Master.
