### ISSUE TITLE
docker-lvm-plugin.conf

### ISSUE THREAD

**Issue by rhatdan** [shishir-a412ed/docker-lvm-driver#14]
Give me an example of creating a VOLUME_GROUP.  What is the lvs commands to create it.

**Comment by shishir-a412ed** [comment]
@rhatdan Should I add this in README.md and man pages too ?

**Comment by rhatdan** [comment]
Yes, You and @rhgoyal are the only ones on the team who know how to do this.

**Comment by shishir-a412ed** [comment]
@rhatdan 
I have updated `docker-lvm-plugin.conf` with an example.
I have also updated the README.md and man pages.

**Comment by rhatdan** [comment]
LGTM.
