### ISSUE TITLE
config location

### ISSUE THREAD

**Issue by runcom** [shishir-a412ed/docker-lvm-driver#15]
```
lvmVolumesConfigPath = "/etc/lvmVolumesConfig.json"
lvmCountConfigPath   = "/etc/lvmCountConfig.csv"
```

can we move those to /var/lib/docker-lvm ? any particular reasons they should clutter /etc?

**Comment by shishir-a412ed** [comment]
+1 we should move this under `/var/lib/docker-lvm`.
@rhatdan what do you think ?

**Comment by rhatdan** [comment]
If content is created by docker-lvm then it should be under /var/lib/docker-lvm.  If content needs to be edited by a Human Being it should be in /etc.  BTW This content should be readonly to the plugin.

**Comment by shishir-a412ed** [comment]
@rhatdan `docker-lvm-plugin` needs to both READ and WRITE on these config files.
You mean this content should not be accessed by anyone else, other than the plugin ?

**Comment by rhatdan** [comment]
If docker-lvm-plugin is writing the files they are not config, they are data files.  Config files are where you store VOLUME_GROUP=

**Comment by shishir-a412ed** [comment]
@rhatdan yes these are files for persisting the state of the memory stores on disk. So yeah agreed these are data files. I ll move them to `/var/lib/docker-lvm`

**Comment by rhatdan** [comment]
Great.

**Comment by shishir-a412ed** [comment]
Fixed in Master.
