### ISSUE TITLE
csv to json

### ISSUE THREAD

**Issue by runcom** [shishir-a412ed/docker-lvm-driver#16]
any reasons to use csv instead of json? can't you accomplish the same? I'm saying this to stick to a format instead of having yet another type of config (even if it's internal/debugging)

**Comment by shishir-a412ed** [comment]
@runcom you cannot JSON encode a map whose key is not string.

**Comment by runcom** [comment]
@shishir-a412ed I see this, I'm saying, could we index those with strings to get a consistent format?

**Comment by runcom** [comment]
maybe index them by the first field in the csv

**Comment by shishir-a412ed** [comment]
@runcom 
IMHO, I don't have any particular restrictions in using two different formats (JSON and CSV). This is an underlying detail and it should not bother the end user. Encoding both the memory stores as JSON would require to change the Count store format (as the key is not string). This would require some reimplementation (This one is already tested and working).

However if everyone wants this, I ll change it.

**Comment by shishir-a412ed** [comment]
On second thought, Count store does not necessarily need the entire volume object (*v) as a key. Just the volume name should be able to uniquely identify the record. So I changed the encoding to JSON.
Now both the memory stores (Volume and Count) are encoded as JSON.

@runcom PTAL.

**Comment by runcom** [comment]
seems ok

**Comment by shishir-a412ed** [comment]
Fixed in Master.
