### ISSUE TITLE
docker-lvm-plugin.service

### ISSUE THREAD

**Issue by rhatdan** [shishir-a412ed/docker-lvm-driver#17]
Can this be socket activated.  I really do not want this service running all the time, if no one is using docker CLI.  We need to make sure plugins can be socket activated.

**Comment by shishir-a412ed** [comment]
Added on-demand socket activation for this plugin.
@rhatdan I tested it and it works. Thanks @runcom !!

**Comment by runcom** [comment]
:smile:
