### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by rhatdan** [shishir-a412ed/docker-lvm-driver#18]
Don't I need to actually modify /etc/sysconfig/docker to get your volume pluigin to work?

**Comment by runcom** [comment]
can we have a default also?

**Comment by shishir-a412ed** [comment]
@rhatdan I didn't updated `/etc/sysconfig/docker` and the plugin was working for me.
What needs to be updated in that config file ?

**Comment by rhatdan** [comment]
Ok great.  I am always confused by the difference between Auth Plugins in Volume Plugins.
