### ISSUE TITLE
standardize plugins installation to /usr/sbin

### ISSUE THREAD

**Issue by runcom** [shishir-a412ed/docker-lvm-driver#23]
https://github.com/shishir-a412ed/docker-lvm-plugin/blob/master/Makefile#L17

this could be `/usr/sbin`

@rhatdan

**Comment by rhatdan** [comment]
@shishir-a412ed We are going to standardize on plugins in /usr/libexec/docker/

**Comment by runcom** [comment]
@rhatdan sorry https://github.com/projectatomic/rhel-push-plugin/issues/3#issuecomment-193838097 /usr/sbin is probably the right choice here cause plugins are root executable(s)

**Comment by shishir-a412ed** [comment]
@runcom @rhatdan 
So is it `/usr/sbin/` or `/usr/libexec/docker` ?

**Comment by runcom** [comment]
still being decided, hang tight :)
