### ISSUE TITLE
avoid panic

### ISSUE THREAD

**Issue by runcom** [shishir-a412ed/docker-lvm-driver#26]
https://github.com/shishir-a412ed/docker-lvm-plugin/blob/master/driver.go#L192

should check for slice index existence before accessing it, also I think it's better to call `strings.SplitN(.., "=", 2)`

If users mess with the conf file we should error out not panic

**Comment by shishir-a412ed** [comment]
This will not panic. 
If user does not provide volume group name (i.e. he does not update the file `/etc/docker/docker-lvm-plugin`)
`vgSlice[1]` would be `""`.

The code will then proceed to https://github.com/shishir-a412ed/docker-lvm-plugin/blob/master/driver.go#L199 and throw the right error here.

**Comment by runcom** [comment]
That will panic if I mess with the config file and remove the equal sign, Im saying go code doesn't have to panic but it must warn that the expected Config file format isnt right, just try removing the equal sign. Unlucky relying on users and saying it won't panic if you don't remove the equal do not suffice here. We need a proper error when Config file isn't parsable
Kernel code doesn't kernel panic when a file isn't parsable (well not always), for instance

**Comment by shishir-a412ed** [comment]
@runcom why would you try to remove the '=' sign :) 
Are you trying to use the product or break it ! 
I understand your concern, but there can be infinite ways of breaking a software. The user should ideally read the manual and use it the right way. At worst, he can miss updating the file, but he should not be deleting stuff for no reason.

**Comment by runcom** [comment]
And that's correct, I'm go code should not panic when a Config file used by a program is not parsable. It should just error out. Panicking in go isn't best practice and may current state.
