### ISSUE TITLE
Don't use /etc/sysconfig/docker-lvm-driver for config

### ISSUE THREAD

**Issue by rhatdan** [shishir-a412ed/docker-lvm-driver#4]
Should be /etc/docker-lvm.conf or something

Also should use NAME Value Pairs
VOLUME_GROUP=myvolumegroup

That will make this future proof.

**Comment by shishir-a412ed** [comment]
Agreed on `/etc/docker/docker-lvm-plugin.conf`. Updating to that.

**Comment by shishir-a412ed** [comment]
Fixed in Master.
