### ISSUE TITLE
Consistant nameing

### ISSUE THREAD

**Issue by rhatdan** [shishir-a412ed/docker-lvm-driver#5]
Pick a name then make sure the executable, systemd unitfiles, socket, config file, man page have the same name.

**Comment by shishir-a412ed** [comment]
@rhatdan 
How about this ?

Binary: docker-lvm-plugin
Systemd unit file: docker-lvm-plugin.service
Config file: /etc/docker-lvm-plugin.conf
Man page: docker-lvm-plugin.8.md

Shishir

**Comment by rhatdan** [comment]
SGTM

**Comment by rhatdan** [comment]
Also rename the github.

**Comment by runcom** [comment]
> Config file: /etc/docker-lvm-plugin.conf

not sure plugins' conf dir is right straight under /etc, @rhatdan /etc/docker/plugins could be better?

**Comment by rhatdan** [comment]
@runcom I am fine with that also.

**Comment by runcom** [comment]
/etc/docker/plugins is used for spec discovery so I take that back, we could have a plugins.conf/ directory where we store plugins configurations

**Comment by shishir-a412ed** [comment]
@runcom 
For configuration file, you mean `/etc/plugins.conf/docker-lvm-plugin.conf` ?

**Comment by runcom** [comment]
@shishir-a412ed I meant `/etc/docker/plugins.conf/docker-lvm-plugin.conf` - however we could have something nicer instead of `plugins.conf` (might wanna look at what others do for this)

**Comment by shishir-a412ed** [comment]
@runcom @rhatdan 
From what I see on my F23, its `/etc/dir/configuration_file`. e.g `/etc/security/time.conf`.
How about `/etc/lvm-plugin/docker-lvm-plugin.conf` ?

**Comment by runcom** [comment]
> How about /etc/lvm-plugin/docker-lvm-plugin.conf ?

I think we don't want to have all those configs scattered in /etc - at devconf we thought about having a consistent, known, location for those plugins conf. Probably /etc/docker/docker-lvm-plugin.conf would be better

**Comment by rhatdan** [comment]
Yes place it under /etc/docker.

**Comment by shishir-a412ed** [comment]
Fixed in Master.
