### ISSUE TITLE
Cleanup /run/docker/plugins/lvm.sock on daemon shutdown

### ISSUE THREAD

**Issue by shishir-a412ed** [shishir-a412ed/docker-lvm-driver#9]
If a user kills (Ctrl+C) the daemon or does `systemctl stop lvm-plugin` systemd send a SIGINT to the daemon. Catch the signal and remove the `/run/docker/plugins/lvm.sock` file.

**Comment by shishir-a412ed** [comment]
Fixed in Master.

**Comment by runcom** [comment]
@shishir-a412ed why this? can't we leave that there and try to see if volume plugins can be used with socket activation?

**Comment by runcom** [comment]
ping @rhatdan

**Comment by shishir-a412ed** [comment]
@runcom somehow when I stop the `docker-lvm-plugin` daemon `(systemctl stop docker-lvm-plugin)`
and If the `lvm.sock` file is lying around. docker keeps trying to connect to it. So when I do `docker volume ls` it basically hangs (timeout and keep retrying) eventhough there are local volumes (/var/lib/docker/volumes) present

I discussed this with @rhatdan.

**Comment by runcom** [comment]
@shishir-a412ed can we investigate why this is happening and maybe work with upstream to fix this?

**Comment by rhatdan** [comment]
Shutting down the service should remove the sock file.  But I think this should  be opened as an issue with docker.

**Comment by runcom** [comment]
@rhatdan indeed (read my comment above)

**Comment by rhatdan** [comment]
Do you add a --volume-plugin flag to docker  daemon

**Comment by rhatdan** [comment]
I would like to see this socket activated.  One problem would be as soon as you start docker does it ping the socket anyways?  Or just when a volume command or container uses a volume?
